name: Demo Delivery vs Deployment

on:
  push:
    branches: [ main ]

jobs:

  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout mã nguồn
      uses: actions/checkout@v4
    - name: Cài đặt Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
    - name: Chạy tự động các bài Test
      run: node test.js

  continuous-delivery-staging:
    needs: continuous-integration
    runs-on: ubuntu-latest
    environment:
      name: staging 
    steps:
    - name: Deploy to Staging Server
      run: echo "Đã tự động chuyển giao sản phẩm lên môi trường STAGING để QA test thử!"

  continuous-delivery-production:
    needs: continuous-delivery-staging
    runs-on: ubuntu-latest
    environment:
      name: production-delivery 
    steps:
    - name: Deploy to Production via Approval
      run: echo "Sếp đã bấm nút Duyệt! Code chính thức lên môi trường PRODUCTION của Delivery."


  continuous-deployment-production:
    needs: continuous-integration
    runs-on: ubuntu-latest
    steps:
    - name: Deploy straight to Production
      run: echo "Không cần ai duyệt cả! Code tự động bay thẳng lên PRODUCTION của Deployment."