# name: Continuous Deployment
# on:
#   push:
#     branches: [ main ]
# # on:
# #   workflow_dispatch:

# permissions:
#   contents: write
#   pages: write
#   id-token: write

# jobs:
#   continuous-integration:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Cài đặt Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '24'
#     - name: Run test
#       run: node test.js

#   continuous-deployment:
#     needs: continuous-integration
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4

#     - name: Cấu hình GitHub Pages
#       uses: actions/configure-pages@v4

#     - name: Đóng gói các file
#       uses: actions/upload-pages-artifact@v3
#       with:
#         path: '.'

#     - name: Triển khai
#       uses: actions/deploy-pages@v4